version: "2"

services:
    mongo:
        image: mongo

    redis:
        image: redis

    backend:
        image: tdlserver
        build: Server
        environment:
            - GARUDA_MONGO_HOST=mongo
            - GARUDA_REDIS_HOST=redis
        depends_on:
            - redis
            - mongo
        ports:
            - 3000:3000
