version: "2"

services:
    mongo:
        image: mongo
        container_name: tdlmongo

    redis:
        image: redis
        container_name: tdlredis

    tdlserver:
        image: tdlserver
        environment:
            - GARUDA_MONGO_HOST=mongo
            - GARUDA_REDIS_HOST=redis
        depends_on:
            - redis
            - mongo
        ports:
            - 3000:3000
