version: "2"

services:
    mongo:
      container_name: mongo
      image: mongo

    redis:
       container_name: redis
       image: redis

    tdlserver:
      image: tdlserver
      environment:
       - GARUDA_MONGO_HOST=mongo
       - GARUDA_REDIS_HOST=redis
      depends_on:
       - redis
       - mongo
      ports:
       - 3000:3000
